_name_: s4_simple
d_state: 64
channels: 1
bidirectional: false
activation: gelu
postact: null
initializer: null
weight_norm: false
dropout: ${..dropout} # Same as null
dt_min: 0.001
dt_max: 0.1
lr: 0.001
learn_a: true
learn_theta: true
theta_scale: false
learn_dt: false
zero_order_hold: false
use_initial: false
trap_rule: false
linear: false
skip_connection: true
repr: cont
param_norm: 'none'