# @package _global_
train:
  interval: step
scheduler:
  # _target_: transformers.get_cosine_schedule_with_warmup
  _name_: cosine_warmup_timm
  t_in_epochs: False
  t_initial: 300
  lr_min: 1e-5
  warmup_lr_init: 1e-6
  warmup_t: 10
